[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/YOUR_API_KEY"

[etherscan]
mainnet = { key = "YOUR_ETHERSCAN_API_KEY" }
sepolia = { key = "YOUR_ETHERSCAN_API_KEY" }
